# Travis CI
language: node_js

cache:
  directories:
  - node_modules
  - "$NVM_DIR"

node_js:
- v5
- v4

deploy:
  provider: heroku
  api_key:
    secure: I230kTgdhOJxtjX0smYe01jHj/12u2s2Lh5GDGxHqyts/siYqszdPHe8JPsjixu1K/7cbu7st9/ICHvOpuhFCIFZS45j83bzQWH5hp5o+UJDyvCLJAhTPMm+NZcAlCh51gE9ftBVsFfB5NBzyhw8V7oD2PzO6VzLdm3oHfW/M5XHlqUZ7UnkRKt+ubQ7WfzNhUA0UF50KBlV/k9hj9F1RKtIYUs8nPFELGpBwUdNrdAy8vnoK/W/nMjVT1KeNTHZcr3GrvllZsqOtbuLB6Orfz+KM0Wg6gdds+rofoxFE9kaf4FMWxDsPJ04hf7XScsysms1otfihZIziuGhzGnrI2l7oFRr9zcFf111C4lEA4GGL2HZkMnWGMwNHEXKJjanZ4z5qnTmWbjONRMBdJ4GH609J7aPKn0cxM5RScyrhla7BD1oZ0xT5Jxs3v6ng13bxLh+HboKXvM8gr8Xqn72zktPAdMq5jSPgGeXEQUXPZYCFKpNlJam0XnR5EEljgg17yvuVoHt31bGIldWRZCs6CQiON0CkdOlLw7iSp9tH1V4AMKr2JiaFDxb9yjsB1kFWMnLL7rrAnt6KraRE/4s1zNV+NjanMORSuENBXPqJ9ZDOo025wgat/CnYifUKOQGK/nZt8I28kzkh8UbZwFJKSKtYWf4yCIDHJwKsKmsv5I=
  app: bunto-mention-bot
